[workspace]
resolver = "2"
members = ["rs-double-linked-list", "rs-macro-capturing", "rs-macro-intro", "rs-macro-repeat-pattern", "rs-smart-pointer-circle-ref-risk", "rs-weak-ref", "rs-web-scraping"]
